version: 1.0.1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:180951985672:task-definition/todo-client:2"
        LoadBalancerInfo:
          ContainerName: "todo-client"
          ContainerPort: 80