version: 0.2
phases:
  install:
    runtime-versions:
        docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 180951985672.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t todo-client .
    - docker tag todo-client:latest 180951985672.dkr.ecr.us-east-1.amazonaws.com/todo-client:latest
  post_build:
    commands:
    - echo Build completed on `date`
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker push 180951985672.dkr.ecr.us-east-1.amazonaws.com/todo-client:latest
#artifacts:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
