version: '2'

services:
  client:
    container_name: todo-clients
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '1234:1234'
      - '1235:1235'
    environment:
      - NODE_ENV=development
